In [13]:
import csv
with open('synthetic_mobile_sales_2025.csv','r') as sm:
    lst=csv.DictReader(sm)
    count_sales=0
    total_revenue=0
    brands={}
    revenue_by_month={}
    for line in lst:
        count_sales+=1
        total_revenue+=int(line['Revenue_USD'])
        if line['Brand'] not in brands:
            brands[line['Brand']]=0
        brands[line['Brand']]+=int(line['Revenue_USD'])
        if line['Sale_Month'] not in revenue_by_month:
            revenue_by_month[line['Sale_Month']]=0
        revenue_by_month[line['Sale_Month']]+=int(line['Revenue_USD'])
avg=sum(list(brands.values()))/len(brands)
brands_above_average=dict(filter(lambda x:x[1]>avg,brands.items()))
the_most_active_brand=sorted(brands_above_average.items(),key=lambda x:-x[1])
top_3_months=sorted(revenue_by_month.items(),key=lambda x:-x[1])[:3]
with open('report.txt','w',encoding='UTF-8') as rp:
    rp.write(f'Общее количество продаж:{count_sales}\n')
    rp.write(f'Общая выручка:{total_revenue} USD \n')
    rp.write(f'Средний чек:{total_revenue/count_sales} USD \n')
    rp.write(f'Продажи по брендам:{brands}\n')
    rp.write(f'Бренды выше среднего:{brands_above_average}\n')
    rp.write(f'Самый активный бренд:{the_most_active_brand[0][0]}\n')
    rp.write(f'Выручка по месяцам:{revenue_by_month}\n')
    rp.write(f'Топ-3 месяца:{top_3_months}\n')
    rp.write(f'Самый прибыльный месяц:{top_3_months[0][0]}\n')

In [1]:
from numpy import *
a=array([[1,2,3],
         [4,5,6]])
b=array([1,23,3,56])
print(a)
print()
print(shape(a))
print()
print(transpose(a))
print()
print(sort(b))


[[1 2 3]
 [4 5 6]]

(2, 3)

[[1 4]
 [2 5]
 [3 6]]

[ 1  3 23 56]


In [31]:
for x in range(65, 95):
    print(f"Код {x} — это символ: {chr(x)}")

Код 65 — это символ: A
Код 66 — это символ: B
Код 67 — это символ: C
Код 68 — это символ: D
Код 69 — это символ: E
Код 70 — это символ: F
Код 71 — это символ: G
Код 72 — это символ: H
Код 73 — это символ: I
Код 74 — это символ: J
Код 75 — это символ: K
Код 76 — это символ: L
Код 77 — это символ: M
Код 78 — это символ: N
Код 79 — это символ: O
Код 80 — это символ: P
Код 81 — это символ: Q
Код 82 — это символ: R
Код 83 — это символ: S
Код 84 — это символ: T
Код 85 — это символ: U
Код 86 — это символ: V
Код 87 — это символ: W
Код 88 — это символ: X
Код 89 — это символ: Y
Код 90 — это символ: Z
Код 91 — это символ: [
Код 92 — это символ: \
Код 93 — это символ: ]
Код 94 — это символ: ^


In [32]:
print(ord("5"))  # Выведет 53 (код символа)
print(chr(53))   # Выведет '5' (сам символ)

53
5


In [75]:
import itertools as itr
a=[x for x in range(1,2)]
b=list(itr.permutations(a,r=2))
print(b)

[]
